id: opecha:P003031
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8586
  title: མངོན་པ་མཛོད་ཀྱི་དགོངས་དོན་གསལ་བྱེད་ལེགས་བཤད་ཉིན་བྱེད་སྣང་བ། （བོད་ལྗོངས་མི་དམངས་དཔེ་སྐྲུན་ཁང་།）
  volume: ''
  author: ''
